# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx
  matrix:
    include:
      - osx_image: xcode11.6
      - osx_image: xcode12.4
      - osx_image: xcode13.3
environment:
  global:
    WARNINGS_ARE_ERRORS: 1

after_success:
  - Rscript -e 'covr::coveralls(type = "all")'
