---
title: "Constant_muscle_mass"
author: "Brian Masinde (brima748)"
date: "11/5/2019"
output: pdf_document
---

```{r}
# load functions
devtools::load_all()

data("birds")

```

```{r}
hirundo_rustica <- birds[9 , ]

bodyMass <- hirundo_rustica$Empty.mass

fatMass <- hirundo_rustica$Fat.mass

wingSpan <- hirundo_rustica$Wing.span

wingArea <- hirundo_rustica$Wing.area

ordo<- hirundo_rustica$Order
```


```{r}
cons <- list(
    # profile power constant
    ppcons = 8.4,

    # energy content of fuel per kg
    energy = 3.9 * 10 ^ 7,

    # accelaration due to gravity
    g = 9.81,
    # mechanical conversion efficiency  [0,1]
    n = 0.23,

    # induced power factor
    k = 1.20,

    # ventilation and circulation power (Tucker's data)
    R =  1.10,

    # air density at fligh height
    airDensity = 1.00,

    # body drag coefficient
    bdc = 0.10,

    # constant varies btw passerines and non-passerines
    alpha = c(6.25, 3.79),

    delta = c(0.724, 0.723),

    # consumption
    consume = 1
  )
```

```{r}
cons_speed <- function(bodyMass, fatMass, wingSpan, wingArea, ordo, cons) {
  
  bm <- c()
  bm[1] <- bodyMass
  fm <- c()
  fm[1] <- fatMass
  D <- c()
  D[1] <- 0
  sd <- c()
  minspd <- c()
  rvvmp <- c()
  currentFM <- fatMass
  i <- 1
  while (currentFM > 0) {
    # find speed and power
    vmp <- .min.pow.speed(bm[i], wingSpan, cons)
    
    minspd[i] <- vmp
    
    speed <- vmp * 1.2
    
    sd[i] <- speed
    
    rvvmp[i] <-  speed/vmp
    
    power <- .total.mech.power(bm[i], wingSpan, wingArea, speed, cons)
    
    # chemical power
    E <- (power / cons$n + .basal.met2(cons, bm[i], fm[i], ordo)) * cons$R
    
    # increase E by 10% to account for respiratory and heart
    #E <- E + (E * 0.1)
    
    # update body
    massDep <- (E/cons$energy) * 360
    
    fm[i + 1] <- fm[i] - massDep
    bm[i + 1] <- bm[i] - massDep
    
    currentFM <- fm[i] - massDep
    D[i + 1] <- D[i] + speed * 360
    # increment counter
    i <- i + 1
  }
  
  return(list(bm, fm, D, sd, minspd, rvvmp))
}
```

```{r}
cs <- cons_speed(bodyMass, fatMass, wingSpan, wingArea, ordo, cons)
```



```{r}
Dist <- cs[[3]]

Dist[length(Dist)]/1000
```

```{r}
minspd <- cs[[5]]

minspd[length(minspd)]

minspd[1]
```

```{r}
ratiovvmp <- cs[[6]]

ratiovvmp[1]

ratiovvmp[length(ratiovvmp)]
```

