# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.basal_metabolic_pow <- function(airframeMass, muscleMass, taxon, alphaPasserines, alphaNonPasserines, deltaPasserines, deltaNonPasserines) {
    .Call('_flying_basal_metabolic_pow', PACKAGE = 'flying', airframeMass, muscleMass, taxon, alphaPasserines, alphaNonPasserines, deltaPasserines, deltaNonPasserines)
}

.minpowspeed_cpp <- function(bm, ws, ipf, g, airDensity, bdc) {
    .Call('_flying_minpowspeed_cpp', PACKAGE = 'flying', bm, ws, ipf, g, airDensity, bdc)
}

.mechanical_power <- function(bm, ws, wa, tas, g, airDensity, ipf, bdc, ppc) {
    .Call('_flying_power_curve', PACKAGE = 'flying', bm, ws, wa, tas, g, airDensity, ipf, bdc, ppc)
}

.total_Mech_Pow_cpp <- function(bm, ws, wa, vt, g, airDensity, ipf, bdc, ppc) {
    .Call('_flying_total_Mech_Pow_cpp', PACKAGE = 'flying', bm, ws, wa, vt, g, airDensity, ipf, bdc, ppc)
}

