# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function calculates the minimum power speed
#' @param bm all-up mass
#' @param ws wing span
#' @param ipf induced power factor
#' @param g gravity
#' @param airDensity
#' @param bdc body drag coefficient
#' @export
.minpowspeed_cpp <- function(bm, ws, ipf, g, airDensity, bdc) {
    .Call(`_flying_minpowspeed_cpp`, bm, ws, ipf, g, airDensity, bdc)
}

#' Function calculates total mechanical power
#' @param bm body mass
#' @param ws wing span
#' @param wa wing area
#' @param vt true speed
#' @return totalMechPower total mechanical power
#' @export
NULL

.total_Mech_Pow_cpp <- function(bm, ws, wa, vt, g, airDensity, ipf, bdc, ppc) {
    .Call(`_flying_total_Mech_Pow_cpp`, bm, ws, wa, vt, g, airDensity, ipf, bdc, ppc)
}

